apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: persistent-volumes-argo
  labels:
    grafana_dashboard: "1"
    project: "foo"
data:
  {{-/* Note, indent of only two spaces */}}
  config.txt: |-
{{ .Files.Get "config.txt" | indent 4 }}
{{/* .Get, not .Glob; indent 4 spaces, more than 2 above */}}