---
apiVersion: v1
kind: ConfigMap
metadata:
  name: file-grafana-check
data:
  grafana-check.yaml: |-
    init_config:
    instances:
      - name: GrafanaCheck
        url: https://grafanacashalm.dev.gc.container.btgpactual.net/api/health
        method: get
        service: gc-grafana-dev
        min_collection_interval: 900
        content_match: '\"database\"\: \"ok\"'

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - name: guestbook-ui
        image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: agent-config-httpcheck
          mountPath: /usr/agent-datadog/config.d/http-check.d/grafana-check.yaml
          readOnly: true
          subPath: grafana-check.yaml
      volumes:
      - name: agent-config-httpcheck
        configMap:
          defaultMode: 0700
          name: file-grafana-check