---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  grafana-check.yaml: |-
    primeira linha
    segunda linha
    terceira linha
    quarta linha
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - name: guestbook-ui
        image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: configmap-volume
          mountPath: /usr/agent-datadog/config.d/http-check.d/grafana-check.sh
          readOnly: true
          subPath: grafana-check.sh
      volumes:
      - name: configmap-volume
        configMap:
          defaultMode: 0700
          name: my-configmap